print("Welcome to PyCor Setup")
print("This installation will install the latest version of PyCor if you downloaded through a .zip file.")
print("Please locate your .zip file if you downloaded via GitHub:")
fileLocation = input("Location: C:/Users/")
print("Extracting files...")
print("Installing...")
print("The file is safe to extract now.")
input("Press Enter to exit")
exit(0)